### ISSUE TITLE
No Data without sending data first

### ISSUE THREAD

**Issue by grantstephens** [epiclabs-io/esphome-modbus-server#2]
Hi

Firstly- thank you for this component- it is exactly what I need.

I'm having a bit of a weird issue- I know that my interface is connected correctly as I get data via the mbpoll tool (https://github.com/epsilonrt/mbpoll), but when I apply the following config then there seems to be no data via the uart interface:
```
esphome:
  name: ashp
esp32:
  board: nodemcu-32s

wifi: !include wifi.yaml
api:

logger:
  level: VERBOSE
ota:
uart:
  - rx_pin: GPIO23
    tx_pin: GPIO22
    baud_rate: 19200
    stop_bits: 2
    data_bits: 8
    id: hpuart
    parity: NONE
    debug:
      direction: BOTH

modbus_server:
  - id: modbuserver
    uart_id: hpuart
    address: 1 # slave address
    holding_registers:
      - start_address: 1 # starting register range
        default: 0 # default value for all those registers
        number: 10 # number of registers in the range
        on_read: | # called whenever a register in the range is read
          // 'address' contains the requested register address
          // 'value' contains the stored register value
          ESP_LOGD("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value; // you can return the stored value or something else.
```
With this config there is no data that comes via the uart debugging logs or via the `ESP_LOGD` command in the `on_read` section.

**Comment by That-Dude** [comment]
Which modbus transceiver are you using?

If its a MAX485 it sounds like your dataflow pin(s) and held low which would lock it into receive only. 

This is the problem in the two other open issues.

The code author seems unresponsive.
