### ISSUE TITLE
How to understand the guide?

### ISSUE THREAD

**Issue by StarChildDK** [epiclabs-io/esphome-modbus-server#5]
This is in the guide:
holding_registers:
      - start_address: 79 # starting register range
        default: 82 # default value for all those registers
        number: 10 # number of registers in the range
        on_read: | # called whenever a register in the range is read
          // 'address' contains the requested register address
          // 'value' contains the stored register value 
          ESP_LOGI("ON_READ", "This is a lambda. address=%d, value=%d", address, value);
          return value; // you can return the stored value or something else.

Let's say I want to return these holding registers:
Address 	Value
200  		398.413330   
202  		396.458252          
204  		396.623444   

How should I do that, like this?:

holding_registers:
      - start_address: 200 # starting register range
        default: 82 # default value for all those registers
        number: 3 # number of registers in the range
        on_read: | # called whenever a register in the range is read
          // 'address' contains the requested register address
          // 'value' contains the stored register value 
          ESP_LOGI("ON_READ", 200, 398.413330);
          ESP_LOGI("ON_READ", 202, 396.458252);
          ESP_LOGI("ON_READ", 204, 396.623444);
          return value; // you can return the stored value or something else.

Or how? I really hope you will specify for me.

**Comment by StarChildDK** [comment]
Anyone?

**Comment by That-Dude** [comment]
If you need to return an integer such as 398 you would setup a single register like this:

```
holding_registers:
- start_address: 200
default: 398 # default value of register
number: 1
on_read: |
return value; // will return 398, which is set in default above.
```

If you need to return as float such as 398.413330, you would could setup two registers  like this:

```
holding_registers:
- start_address: 200
default: 398 # default value of register
number: 1
on_read: |
return value; // will return 398, which is set in default above.

holding_registers:
- start_address: 201
default: 413330 # default value of register
number: 1
on_read: |
return value; // will return 413330, which is set in default above.
```

Now when you polling device calls for regs 200 and 201 it will receive 398 and 413330 which it interprets as a float.

You can test this by building a simple modbus network with you esp device on one end and a laptop with modbus poll on the other end https://www.modbustools.com/download.html

**Comment by StarChildDK** [comment]
Thank you so much!! 
Now I just have to figure out how to parse a HA value as an int. :)

**Comment by jpeletier** [comment]
Thank you @That-Dude for your reply.

The component could be improved to simulate "float" registers, but that's a TODO.
